### ISSUE TITLE
util.STREAM_STDERR => could not launch (Windows 10?)

### ISSUE THREAD

**Issue by Pendrokar** [SublimeLinter/SublimeLinter-xmllint#8]
```
SublimeLinter: xmllint activated: C:\tools\libxml\xmllint.exe 
SublimeLinter: xmllint linter reloaded 
SublimeLinter: xmllint: sample.xml ['C:\\tools\\libxml\\xmllint.exe', '--noout', '-'] 
SublimeLinter: ERROR: could not launch ['C:\\tools\\libxml\\xmllint.exe', '--noout', '-'] 
SublimeLinter: reason: [Errno 2] No such file or directory 
```

Another Linter is working fine for me, but not this one. Could it have something to do with Windows 10?

If I change within linter.py:
`error_stream = util.STREAM_STDERR`
to
`error_stream = util.STREAM_BOTH`

This fixes the problem.

**Comment by braver** [comment]
This is Pre-SublimeLinter4, we deal with errors differently nowadays.
